# Generated by Django 4.2 on 2023-05-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombreProdc', models.CharField(max_length=120)),
                ('marca', models.CharField(max_length=15)),
                ('modelo', models.CharField(max_length=15)),
            ],
        ),
    ]
